### ISSUE TITLE
Using Google Chrome, when a scenario starts the simulation goes white. 

### ISSUE THREAD

**Issue by aidenmitchell** [mattbradley/dash#1]
Using Google Chrome, when a scenario starts the simulation goes white. The speed numbers in the top left hand corner are still visible, and they update too.

**Comment by aidenmitchell** [comment]
Here's a GIF of the problem: https://gyazo.com/5e46c4d167018e371b65eb8d4b0027c6

**Comment by aidenmitchell** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30846409/53774120-1df91d00-3ea2-11e9-9bc0-f75afd313b0f.gif)

**Comment by AegonWei** [comment]
Did you fix it?

**Comment by aidenmitchell** [comment]
Any updates?

**Comment by aidenmitchell** [comment]
Closing issue, it has now starting working for me. Update your Chrome to the latest version.
